### ISSUE TITLE
PUBLIC NOTICE: Azure Storage Python 0.30 Release

### ISSUE THREAD

**Issue by jehine-MSFT** [Azure/azure-storage-python#132]
We are pleased to announce the 0.30 preview release of the [Azure Storage Python Client Library](https://github.com/Azure/azure-storage-python/). With this version comes all features included in the 2015-04-05 REST version including support for the following features:
- Append Blob support
- File service support
- Lazy Enumeration for listing APIs
- Account SAS support
- Table Batch refactors
- JSON Table formatting support

The team has worked to address many of the customer concerns and gaps to bring it up parity with our other libraries. Please see our [Getting Started Docs](https://azure.microsoft.com/en-us/documentation/articles/?service=storage&platform=python) to check out all of these new features. The 0.30 release has many breaking changes, so to help transition from older versions of the library please review our [latest reference documentation](http://azure.github.io/azure-storage-python/), [upgrade guide](http://azure.github.io/azure-storage-python/upgrade.html), [usage samples](https://github.com/Azure/azure-storage-python/tree/master/samples) and [Breaking Changes](https://github.com/Azure/azure-storage-python/blob/master/BreakingChanges.md) log.
As always, we will continue to do our work in the public GitHub dev branch for visibility and transparency. Please let us know if you have any concerns or suggestions with the new library as community feedback is very important to us.

Thank you,
The Azure Storage Team

**Comment by emgerner-msft** [comment]
For those curious, some of the major features being considered for the next couple releases are:

1. Retry by default for transient errors. Retry policy support for custom retry logic. This will help with 2. since rather than failing the request on transient connection issues we'll retry if we have time and in many cases the issue should resolve itself.
2. Client side timeout. Better timeout handling on the socket connection. Max execution time managed across multiple service requests. (#17, #65)
3. MD5 calculation for upload and download. Off by default, but a bool to turn it on rather than requiring folks calculate and pass the MD5 themselves. (#99, #11)
4. Some form of setting/getting client request id from requests as well as setting other custom headers. (#15)

The work for all of these will be done in the public dev branch. As JC mentioned above: Please let us know if you have any concerns or suggestions with the library!

**Comment by emgerner-msft** [comment]
[0.32.0](https://github.com/Azure/azure-storage-python/releases/tag/v0.32.0) solves 3 and 4. It also fixes some bugs and adds a couple other features.
