### ISSUE TITLE
QueueService endpoint_suffix does not work

### ISSUE THREAD

**Issue by chenghsiang** [Azure/azure-storage-python#146]
While using the QueueService with endpoint_suffix as below:
qs = QueueService(
    account_name=account_name,
    account_key=key1,
    endpoint_suffix='.queue.core.windows.net')
When I tried to create a message queue, or list queues, I got the following errors:
>>> qs.create_queue(queue_name)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/queue/queueservice.py", line 452, in create_queue
    response = self._perform_request(request)
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/storageclient.py", line 137, in _perform_request
    raise AzureException('{}: {}'.format(ex.__class__.__name__, ex.args[0]))
azure.common.AzureException: InvalidURL: URL has an invalid label.

Note, if I don't give the optional parameter "endpoint_suffix", there is NO issue.
Is this a known bug or I missed something?

**Comment by emgerner-msft** [comment]
If you check [the docs](http://azure.github.io/azure-storage-python/ref/azure.storage.queue.queueservice.html) in the queue service about endpoint suffix, you'll see examples: "Defaults Azure (core.windows.net). Override this to use the China cloud (core.chinacloudapi.cn)." Similarly, if you check the existing default value for endpoint_suffix, it equals 'core.windows.net' as promised in the docs. 

So, the endpoint suffix you're using is not formatted correctly which results in the URL not resolving. If you switch to 'core.windows.net', the existing default, everything works fine. However since it's the default, there's no real point to specifying this. If you'd like to use the China endpoint, use 'core.chinacloudapi.cn'.
