### ISSUE TITLE
azure.storage.QueueMessage considered harmful

### ISSUE THREAD

**Issue by crwilcox** [Azure/azure-storage-python#16]
### Description:
This week I wrote code addressing Azure Storage Blobs, Tables and Queues. Great stuff. Since I ran into errors while removing message that were dequeued more often than my limit, I looked into the details of azure.storage.QueueMessage. The implementation was surprising me...

azure.storage.QueueMessage is just a bunch of strings. I was really surprised that this class (obviously nothing more than a Data Transfer Object) ships with an SDK that is marked as 'production/stable/ on PyPI. 

class QueueMessage(WindowsAzureData):

    ''' Queue message class. '''

    def __init__(self):
        self.message_id = u''
        self.insertion_time = u''
        self.expiration_time = u''
        self.pop_receipt = u''
        self.time_next_visible = u''
        self.dequeue_count = u''
        self.message_text = u''

I would expect members having names containing 'time' to have type DateTime and members having names indicating an integer (dequeue_count) to be an Integer. Instances of this class are just prone to error. That's what happened to me.

Focused Python developers may expect a standard-level pythonic API coming from Microsoft that of course will hide transport implementations details as well that are discussed in this issue [https://github.com/Azure/azure-sdk-for-python/issues/150]. 

Can anybody comment this or explain why it is like that or even has to be like that? Any suggestions how to contribute on that important topic without breaking APIs are welcome.

**Comment by jehine-MSFT** [comment]
We have made improvements to our Queue models to address the issues you discussed above. We are Also working on fixing the issue you linked to involving queue encoding/decoding.
Our next major release will contain updates that will make working with the Azure Queue service much improved.

**Comment by emgerner-msft** [comment]
We have released the 0.30 version (#132) which addresses this feature request.

The defaults for the various settings are now 'None', but you an see in the [docs for QueueMessage](https://github.com/Azure/azure-storage-python/blob/master/azure/storage/queue/models.py#L51) that the types have been updated. 

Not only queue, but the entire library has been updated to parse into the expected type rather than using strings. 

Take a look and tell us what you think!

**Comment by saschagottfried** [comment]
Hi Emily,
I thinks this is great news. I have been watching this issue ever since. I am pretty surprised that it was eventually fixed. The 0.30 version looks promising, I already skimmed through the docs. Honestly, I will not have the time to review my code that used the older version (azure-python <= 0.10) during next weeks. 

If that will happen I will let you know somehow - even if this issue is closed then.

I actually like the effort Microsoft employees put into a Python SDK for its cloud service. Keep up "thinking in python"!

**Comment by emgerner-msft** [comment]
Thanks! We really appreciate the time it takes to give more general feedback like this and we completely understand if you don't have time at the moment. For now I'll close this issue, but if/when you do have time to take a look, please open this again or open up a new issue.
