### ISSUE TITLE
Add has_container_name to *BlobService

### ISSUE THREAD

**Issue by boumenot** [Azure/azure-storage-python#179]
It would be nice if the BlobService class had a method called has_container_name. I'm not sure if the request is more appropriate for here or Swagger.

I'm moving this issue over from the [SDK](https://github.com/Azure/azure-sdk-for-python/issues/622).

**Comment by emgerner-msft** [comment]
What would this API do?

**Comment by emgerner-msft** [comment]
Ping...

**Comment by boumenot** [comment]
Sorry for the delay, I was on vacation.

It's a common operation to check for the existence of a container before taking a operation against a container, or checking if a container exists before creating it.

The method might be implemented like the following.

```python
    def has_container_name(self, container_name):
        exists = any(x for x in self.list_containers() if x.name == container_name)
        return exists
```

**Comment by emgerner-msft** [comment]
1) If try to create a container and it already exists, the server will throw an error and the API will by default swallow the error and return False. Nothing about the container will change. You can tell the API to throw instead by using the [fail_on_exist flag](https://github.com/Azure/azure-storage-python/blob/master/azure/storage/blob/baseblobservice.py#L521). 

2) There's already a method that does exactly what you're looking for which is named using a word in your description: [exists](https://github.com/Azure/azure-storage-python/blob/master/azure/storage/blob/baseblobservice.py#L1483). It does a get on the container instead of listing, as listing all the containers to find a single one could be extremely slow if you have a lot of containers. Samples for this operation and create are in the [samples folder](https://github.com/Azure/azure-storage-python/blob/master/samples/blob/container_usage.py#L137).

**Comment by boumenot** [comment]
Thanks @emgerner-msft!  I should have done a better job reading the API.
