### ISSUE TITLE
Unhelpful error when inadvertently adding more than the max allowed ACL entries

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-storage-python#181]
``` Python
from azure.storage.blob import BlockBlobService
from azure.storage.models import AccessPolicy

cs = 'blah'
rg = 'blah'
sa = 'blah'
container = 'blah'

client = BlockBlobService(connection_string=cs)

client.create_container(container)
acl = {'1': AccessPolicy(permission='r')}
acl['2'] = AccessPolicy(permission='w')
acl['3'] = AccessPolicy(permission='d')
acl['4'] = AccessPolicy(permission='l')
acl['5'] = AccessPolicy(permission='rwdl')
acl['6'] = AccessPolicy(permission='rl')
client.set_container_acl(container, acl)
```

This triggers the following:

```
Traceback (most recent call last):
  File "C:\Users\trpresco\Documents\github\azure-cli\src\azure\acl_bug_repro.py", line 21, in <module>
    client.set_container_acl(container, acl)
  File "c:\users\trpresco\documents\github\azure-cli\env\lib\site-packages\azure\storage\blob\baseblobservice.py", line 743, in set_container_acl
    response = self._perform_request(request)
  File "c:\users\trpresco\documents\github\azure-cli\env\lib\site-packages\azure\storage\storageclient.py", line 125, in _perform_request
    _storage_error_handler(ex)
  File "c:\users\trpresco\documents\github\azure-cli\env\lib\site-packages\azure\storage\_serialization.py", line 130, in _storage_error_handler
    return _general_error_handler(http_error)
  File "c:\users\trpresco\documents\github\azure-cli\env\lib\site-packages\azure\storage\_error.py", line 71, in _general_error_handler
    raise AzureHttpError(message, http_error.status)
azure.common.AzureHttpError: XML specified is not syntactically valid.
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidXmlDocument</Code><Message>XML specified is not syntactically valid.
RequestId:cfe4e8be-0001-0108-43da-bd6d50000000
Time:2016-06-03T20:56:07.1909467Z</Message><LineNumber>0</LineNumber><LinePosition>0</LinePosition><Reason /></Error>
```

There's a disconnect between the problem--exceeding the max allowed ACL entries--and the error message given. To avoid hard coding the MAX_ENTRIES into our application (since it could change) it would be helpful if the SDK thew an error stating that the maximum number of entries has been exceeded (and specifying the current MAX_ENTRIES value).

**Comment by emgerner-msft** [comment]
In the long run this is something that will be fixed on the server. A bug is logged.

In general, we avoid these sort of checks on the client for future compatibility. Say the service started allowing 10 ACLs (theoretically) and we had a check in the library to only allow 5. We'd not only not allow valid requests, but we'd also make it impossible to update since if they got a 10 ACL list, modified it, and then tried to put it, it wouldn't work. Basically, putting it in our SDK has the exact same issue as you hard coding it in your application.

In this case after evaluating the error message we'll take a temporary fix to the client until the server updates it's message. Once that's released, we'll likely remove this.

**Comment by zezha-msft** [comment]
I'm closing this for now. If the behavior changes on the service side in a future service version, the SDK will be updated accordingly.
