### ISSUE TITLE
azure.storage.blob package documentation is empty.

### ISSUE THREAD

**Issue by zfrenchee** [Azure/azure-storage-python#196]
I'm looking for information about the python BlobService API. [Read the Docs](http://azure-storage.readthedocs.io/en/latest/ref/azure.storage.blob.html) documentation is broken in a couple ways. 

The first of those links on that page leads [here](http://azure-storage.readthedocs.io/en/latest/ref/azure.storage.blob.blobservice.html) which has nothing on it. Moreover the link to github on that page is broken.

Is this documentation in the works?  I don't know this API at all so I can't contribute it for you =(

**Comment by zfrenchee** [comment]
That said, I believe the [github.io](http://azure.github.io/azure-storage-python/ref/azure.storage.blob.html) is working... weird.

**Comment by rambo-msft** [comment]
Hi @zfrenchee,
Yes, we are still in the process of resolving some issues with migrating the docs (see #78).
In the meantime, refer to our [GitHub.io page for Python](http://azure.github.io/azure-storage-python/) and also [BlobService API.](http://azure.github.io/azure-storage-python/ref/azure.storage.blob.blockblobservice.html)

**Comment by zfrenchee** [comment]
Hi @rambo-msft 
Does that mean this is out of date? http://azure-storage.readthedocs.io/en/latest/blob.html
It suggests `from azure.storage.blob import BlobService`
but the github.io documentation suggests that BlobService has been split into `BlockBlobService` and others so in fact the correct thing to do is `from azure.storage.blob import BlockBlobService`
If you could point me in the correct direction that would be supreme!

**Comment by rambo-msft** [comment]
@zfrenchee 
Thanks for pointing that out!
Yes, the method in GitHub.io documentation is the correct approach. To clarify, since version 0.30.0 of the library, the BlobService object was divided into three subservices for the different blob types (BlockBlobService, PageBlobService, AppendBlobService) with common methods in the abstract BaseBlobService that these inherit from.  We did this primarily to reduce confusion when blob-type specific methods were used on the incorrect blob type.

The actual [Blob type](https://msdn.microsoft.com/en-us/library/azure/ee691964.aspx) you may want to use will depend on your specific use case. To get you started, I'd  recommend checking out  [How to use Azure Blob storage from Python](https://azure.microsoft.com/en-us/documentation/articles/storage-python-how-to-use-blob-storage/) for an overview using the BlockBlobService. Also, the included code samples will give you a much better idea on how to leverage each type of Blob.

Hope this clears things up! :-)

**Comment by MattPitlyk** [comment]
I had the same confusion last night. Once I figured out that How to use Azure Blob storage form Python article was the most current, I had no problems.

**Comment by zfrenchee** [comment]
Thanks @rambo-msft . Feel free to close this issue if you think that's appropriate. I'd still love to see the documentation for this brought up to date and if you'd like to keep the issue open until that's the case I'll leave that to you.

**Comment by pemari-msft** [comment]
As we mentioned, we have another issue tracking the readthedocs problem. We'll try to make the documentation story more clear. Thanks for the feedback!
