### ISSUE TITLE
Output format of ACL hard to work with

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-storage-python#201]
Currently, when retrieving the ACL for a share/container, the output format looks like:
```JSON
{
  "item1": {
    "expiry": "...",
    "start": "...",
    "permission": "..."
  },
  "item2": {
    "expiry": "...",
    "start": "...",
    "permission": "..."
  },
}
```
This makes it difficult to work with with external tools like jpterm etc. An alternative structure would be:
```JSON
[
  {
    "name": "item1",
    "expiry": "...",
    "start": "...",
    "permission": "..."
  },
  {
    "name": "item2",
    "expiry": "...",
    "start": "...",
    "permission": "..."
  }
]
```
This is consistent with how object collections are handled on other resources and works much better when trying to use with tools like jpterm.

**Comment by jofriedm-msft** [comment]
Hi @tjprescott 

Can you elaborate on the difficulties caused by the current structure? Also what are the "other resources" that you are referring to?

I took a look at the JMESPath exploration tool and it appears to support writing expressions for named objects.
While it may be more convenient, we want to maintain parity across languages. We would need a large demand for this change to justify implementing this breaking change.

**Comment by tjprescott** [comment]
The breaking change alone means it would not be worth making. 

The simplest difficult is that we use JMESPath to specify a table output format for the CLI. There is no JMESPath expression that I know of that can display the key and it's associated values. We have worked around this issue it by transforming the resulting JSON object manually.
