### ISSUE TITLE
Lacks versioned dependency on cryptography

### ISSUE THREAD

**Issue by waldiTM** [Azure/azure-storage-python#218]
azure-storage does not specify a version for cryptography. With 0.6.1 it fails:

```
  File "/usr/local/lib/python3.4/dist-packages/azure/storage/__init__.py", line 21, in <module>
    from .models import (
  File "/usr/local/lib/python3.4/dist-packages/azure/storage/models.py", line 27, in <module>
    from cryptography.hazmat.primitives.keywrap import(
ImportError: No module named 'cryptography.hazmat.primitives.keywrap'
```

**Comment by waldiTM** [comment]
What puzzles me even more: none of the imported stuff is actually used and all the stuff I did worked fine after removing the imports.

**Comment by ardumont** [comment]
Hello,

> azure-storage does not specify a version for cryptography. 

Indeed.

> With 0.6.1 it fails:...

I reproduced this issue on debian stable (I'm trying to debian package it).
The 0.6.1 version is the actual version packaged from debian (python3-cryptography) on the current stable (jessie).

On a debian-stable:
```
$ lsb_release -a
Distributor ID: Debian
Description:    Debian GNU/Linux 8.5 (jessie)
Release:        8.5
Codename:       jessie
$ apt-cache show python3-cryptography
...
Package: python3-cryptography
Source: python-cryptography
Version: 0.6.1-1
```

I believe this problem won't occurred from cryptography >= 1.1.
Since it's from that moment on that `cryptography.hazmat.primitives.keywrap` module appears.
(I've looked at the git-history of the debian package which imports upstream tarballs, and that module appears at that version).

Note that on debian-testing, since this package is more advanced, there won't be issue about it:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux testing (stretch)
Release:        testing
Codename:       stretch
$ apt-cache show python3-cryptography
Package: python3-cryptography
Source: python-cryptography
Version: 1.5-1
```

At last, there may be not much people bothered by this since they may use pip/pip3 to install their package.

So, i guess your workaround would be to use pip3 yourself for now.
Or, if you already do, try and upgrade your cryptography version, i believe it's:

```
sudo pip3 install cryptography --upgrade
```

But you may have reasons not to ^^.

> What puzzles me even more: none of the imported stuff is actually used and all the stuff I did worked fine after removing the imports.

I can't say much on that part ^^

Cheers,

**Comment by rambo-msft** [comment]
Hi @waldiTM,
Thanks for bringing this to our attention. For now the workaround is as @ardumont stated, but we will look into possibly removing the `cryptography.hazmat.primitives.keywrap` in a future release for full version compatibility, otherwise will fallback on a versioned dependency.

**Comment by danmilon** [comment]
Got bit by this too. If its not used, lets remove the import. If its used, lets add a version range to the dependency.

**Comment by rambo-msft** [comment]
Hi folks, we've added a version dependency with our latest release. Thanks again for bringing this to our attention.
