### ISSUE TITLE
SAS does not work some of the time

### ISSUE THREAD

**Issue by samrudh** [Azure/azure-storage-python#225]
Hi..
I am trying to download a blob file using SAS(shared access signature) (input param: sas_token)
It works some of the time while rest of the time following exception appears:
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
Interestingly, same code works perfectly when Access key of the azure account is used. 
Machine used has: debian linux and Python2.7.
Are there any known limitations of azure python SDK while using SAS?

Samrudha

**Comment by rambo-msft** [comment]
Hi @samrudh,
While this error is seemingly random, take a look at this [MSDN article](https://blogs.msdn.microsoft.com/kwill/2013/08/27/http-403-server-failed-to-authenticate-the-request-when-using-shared-access-signatures/) that explains why this scenario can occur.

If you have some form of web debugging proxy software, you can inspect the HTTP request and look at the Time header to see if this is related to using the SAS in an invalid time frame. Essentially,  the request can fail in this manner due to the time deltas between the SAS-generating machine,  the storage servers, and your local system time.

> Interestingly, same code works perfectly when Access key of the azure account is used. 

Could you provide repro code of how you're downloading your blob with the SAS.

**Comment by samrudh** [comment]
I think the time header is not an issue because I am generating SAS with 
start time = current time - 24 hours. 
Will there be still issue with time?
Also on azure logs I could see network errors. Are these causing the mentioned issue?

**Comment by rambo-msft** [comment]
Hi @samrudh,
Are you by chance using a Stored Access Policy? In which case, it may take up to 30 seconds for it to take effect.
Using the account access key will give you full access to the resource you're trying to request, so that explains the second scenario.

If you can provide the logs, or ideally the request header that would help give us insight on the matter.

**Comment by samrudh** [comment]
i am using Shared access policy.
While generating sas_token, validity time is given as -24 hours to + 48 hours.  Still some of the time, authorization header fail occurs as mentioned in the issue above.

**Comment by jofriedm-msft** [comment]
@samrudh can you run the problematic code through fiddler and share the request and response?

If you have the request ID of a recent repro we can take a look at the server logs if the error details does not provide enough detail.

**Comment by pemari-msft** [comment]
Hi @samrudh -- the validity time is not what @rambo-msft was referring to. There is an up to 30 second delay for the policy to take effect, no matter what the start and end time are. Please wait 30 seconds before using the policy.
