### ISSUE TITLE
File objects returned by list_directories_and_files has `None` metadata

### ISSUE THREAD

**Issue by ochawkeye** [Azure/azure-storage-python#230]
azure-storage==0.33.0
Python 2.7.6
requests==2.11.1

Quite similar inquiry as #192 except `list_directories_and_files` has no `include` input parameter that resolved that one.

If I do:
```python
from azure.storage.file import FileService
fs = FileService(ACCOUNT_NAME, ACCOUNT_KEY)
md = {'val1': 'foo', 'val2': 'blah'}
fs.create_file_from_path(CONTAINER, REMOTE_DIR, LOCAL_FILE, filename, metadata=md)

for fileobject in fs.list_directories_and_files(CONTAINER, REMOTE_DIR):
    print fileobject.name, fileobject.metadata
```

I get `filename None`

But if I do:
```python
for fileobject in fs.list_directories_and_files(CONTAINER, REMOTE_DIR):
    print fileobject.name, fs.get_file_metadata(container, remote_dir, fileobject.name)
```
I get `filename {'val1': 'foo', 'val2': 'blah'}`

Is there a way to retrieve this metadata without that extra call for file objects?

**Comment by jofriedm-msft** [comment]
Hi @ochawkeye, unfortunately we are unable to retrieve metadata directly from list files and directories due to optimizations on the service. As you can see https://msdn.microsoft.com/en-us/library/azure/dn166980.aspx the metadata is not returned so you will need to get the metadata for each object directly.

**Comment by ochawkeye** [comment]
Thank you for the response.
