### ISSUE TITLE
get_page_ranges_diff timesout on large page blobs

### ISSUE THREAD

**Issue by pawpy** [Azure/azure-storage-python#242]
We are seeing read timeout on when `get_page_ranges_diff` is called on page blobs that are either 512G or 1023G (premium storage).

```
  File ".env/local/lib/python2.7/site-packages/azure/storage/blob/pageblobservice.py", line 565, in get_page_ranges_diff
  File ".env/local/lib/python2.7/site-packages/azure/storage/storageclient.py", line 266, in _perform_request
    raise ex
azure.common.AzureException: ReadTimeout: HTTPSConnectionPool(host='<name>.blob.core.cloudapi.de', port=443): Read timed out. (read timeout=11)
```
The socket timeout seems to be set to low value of 11s which is where it seems to fail.  Setting timeout to high value on `get_page_ranges_diff` doesn't seem to have any effect.

I've tried setting this to 60s which seemed to have worked but I think `get_page_ranges_diff` should respect the timeout param (and timesout to infinite is None)

**Comment by rambo-msft** [comment]
This can happen when the page blob is heavily fragmented. Unfortunately increasing the timeout doesn’t always help because the maximum timeout enforced by the service for this operation is not large enough to handle very high fragmentation. Instead, you need to request the page ranges over a subset of the blob, and compose the results.

The problem and solution are detailed (for .NET) in this blog post:
https://blogs.msdn.microsoft.com/windowsazurestorage/2012/03/26/getting-the-page-ranges-of-a-large-page-blob-in-segments/


Here is a Python sample (based off the .NET sample)  to give you an idea of how you can compose the page ranges over subsets/chunks of the blob.

```
def get_page_ranges_diff_chunked(self, start_range, end_range, range_chunk_size, container_name, blob_name, previous_snapshot):
        range_size = end_range - start_range + 1
        if range_size % 512 != 0:
            raise ValueError("Range size must be in a valid 512 byte interval alignment.")
        
        # Now 'iterations' will be the amount of calls to 'get_page_ranges_diff'
        # Evaluation of the [start_range, end_range] are chunked with subsets defined by 'range_chunk_size'
        iterations = range_size / range_chunk_size  
        start_offset = start_range
        page_range_diffs = []
        for i in range(iterations):
            end_offset = start_offset + range_chunk_size - 1
        # Include your desired parameters.
            page_ranges = self.bs.get_page_ranges_diff(
                container_name, blob_name, previous_snapshot, None, start_offset, end_offset)
            page_range_diffs.extend(page_ranges)
            start_offset = start_range + range_chunk_size
        return page_range_diffs
```

**Comment by pawpy** [comment]
@rambo-msft thank you for the response and the python snippet.  We did change our logic fetch the page range diff in chunks.  I apply the diff updates in chunks using `update_page`, but hadn't noticed `get_page_ranges_diff` supports fetching diff in chunks of the blob too.  Closing this.
