### ISSUE TITLE
ImportError: No module named storage.blob

### ISSUE THREAD

**Issue by michaelseto** [Azure/azure-storage-python#262]
from azure.storage.blob import BlockBlobService

block_blob_service = BlockBlobService(account_name='myaccount', account_key='mykey')

block_blob_service.create_container('backups')

Part of my pip freeze ::

pip freeze
appdirs==1.4.0
azure==1.0.3
azure-common==1.1.4
azure-mgmt==0.20.2
azure-mgmt-common==0.20.0
azure-mgmt-compute==0.20.1
azure-mgmt-network==0.20.1
azure-mgmt-nspkg==1.0.0
azure-mgmt-resource==0.20.1
azure-mgmt-storage==0.20.0
azure-nspkg==1.0.0
azure-servicebus==0.20.1
azure-servicemanagement-legacy==0.20.2
azure-storage==0.33.0

The 0.33.0 version is clearly there, why does it keep saying no module named storage.blob?

**Comment by rambo-msft** [comment]
If you check your site-packages folder corresponding to your python installation, you might find there is an azure directory with the storage package missing. (Installation issue.)

I would uninstall `azure` and `azure-common`, and `azure-storage`, and proceed with just installing `azure-storage` with pip which should populate the package directory and dependencies properly.
Let me know if that works.

**Comment by michaelseto** [comment]
Wow! That totally worked! Cheers to you, sir! Thank you!

**Comment by rambo-msft** [comment]
@michaelseto Glad to hear! Cheers.

**Comment by sandeepvaidya** [comment]
I am getting the same error as in Issue #262:
ImportError: No module named storage.blob #262
https://github.com/Azure/azure-storage-python/issues/262

I am in fact trying to run the same code:

```
from azure.storage.blob import BlockBlobService
block_blob_service = BlockBlobService(account_name='myaccount', account_key='mykey')
block_blob_service.create_container('backups')
```

Error: 
$ python azure_github.py
_Traceback (most recent call last):
  File "azure_github.py", line 1, in <module>
    from azure.storage.blob import BlockBlobService
  File "/xxx/yyyyy/azure.py", line 1, in <module>
    from azure.storage.blob import PageBlobService
ImportError: No module named storage.blob_

**1) I am working on a 64 bit RHEL server:**
$ python -c 'import sys,platform; print platform.architecture()[0], sys.maxsize > 2**32'
64bit True
$ python -c 'import struct;print( 8 * struct.calcsize("P"))'
64

**2) I have installed python 2.7 (64bits)**
python -v
$ python -v | grep site-packages
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
# /usr/lib64/python2.7/site.pyc matches /usr/lib64/python2.7/site.py
import site # precompiled from /usr/lib64/python2.7/site.pyc
# /usr/lib64/python2.7/os.pyc matches /usr/lib64/python2.7/os.py
import os # precompiled from /usr/lib64/python2.7/os.pyc

...
..

**3) I have 2 site-packages directories:**

./usr/lib/python2.7/site-packages
./usr/lib64/python2.7/site-packages

and when I install the azure-storage package, it gets installed in  the 
/usr/lib/python2.7/site-packages directory.

$ sudo pip install azure-storage
Collecting azure-storage
  Downloading azure_storage-0.34.2-py2.py3-none-any.whl (187kB)
    100% |████████████████████████████████| 194kB 1.6MB/s
Requirement already satisfied: cryptography in /usr/lib64/python2.7/site-packages (from azure-storage)
Collecting azure-nspkg>=2.0.0 (from azure-storage)
  Using cached azure_nspkg-2.0.0-py2.py3-none-any.whl
Requirement already satisfied: python-dateutil in /usr/lib/python2.7/site-packages (from azure-storage)
Collecting azure-common>=1.1.5 (from azure-storage)
  Using cached azure_common-1.1.5-py2.py3-none-any.whl
Requirement already satisfied: requests in /usr/lib/python2.7/site-packages (from azure-storage)
Requirement already satisfied: idna>=2.1 in /usr/lib/python2.7/site-packages (from cryptography->azure-storage)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python2.7/site-packages (from cryptography->azure-storage)
Requirement already satisfied: setuptools>=11.3 in /usr/lib/python2.7/site-packages (from cryptography->azure-storage)
Requirement already satisfied: ipaddress in /usr/lib/python2.7/site-packages (from cryptography->azure-storage)
Requirement already satisfied: cffi>=1.4.1 in /usr/lib64/python2.7/site-packages (from cryptography->azure-storage)
Requirement already satisfied: packaging in /usr/lib/python2.7/site-packages (from cryptography->azure-storage)
Requirement already satisfied: enum34 in /usr/lib/python2.7/site-packages (from cryptography->azure-storage)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/lib/python2.7/site-packages (from cryptography->azure-storage)
Requirement already satisfied: appdirs>=1.4.0 in /usr/lib/python2.7/site-packages (from setuptools>=11.3->cryptography->azure-storage)
Requirement already satisfied: pycparser in /usr/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography->azure-storage)
Requirement already satisfied: pyparsing in /usr/lib/python2.7/site-packages (from packaging->cryptography->azure-storage)
Installing collected packages: azure-nspkg, azure-common, azure-storage
Successfully installed azure-common-1.1.5 azure-nspkg-2.0.0 azure-storage-0.34.2


**4) In directoy, /usr/lib/python2.7/site-packages**
_azure
azure_common-1.1.5.dist-info
azurelinuxagent
azure_nspkg-2.0.0.dist-info
azure_storage-0.34.2.dist-info_

In directoy, /usr/lib/python2.7/site-packages there are no azure packages.

Shouldn't the azure packages install in lib64 ? Is this causing the ImportError ?

**Comment by MadMax2410** [comment]
It doesn't work for me! :(

I'm working on a Windows Server 2012 with Python 3.6.3.
After doing what rambho told (uninstall azure and azure-common, and azure-storage, and proceed with just installing azure-storage with pip), I got the following azure packages:
```
> pip freeze | grep azure
azure-nspkg==2.0.0
azure-storage-blob==0.37.1
azure-storage-common==0.37.1
azure-storage-file==0.37.0
azure-storage-nspkg==2.0.0
azure-storage-queue==0.37.0
```

When I open a Jupyter notebook and write this:
`from azure.storage.blob import BlockBlobService`

I got the following error:
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-36b3905830d2> in <module>()
----> 1 from azure.storage.blob import BlockBlobService

ModuleNotFoundError: No module named 'azure.storage'
```

In my laptop (Windows 7), I have the following packages:
azure-common==1.1.8
azure-nspkg==2.0.0
azure-storage-blob==0.37.1
azure-storage-common==0.37.1
azure-storage-file==0.37.0
azure-storage-nspkg==2.0.0
azure-storage-queue==0.37.0

and it works like a charm.

What's wrong?!

**Comment by zezha-msft** [comment]
Hi @MadMax2410, I noticed that you're missing "azure-common" in your first pip freeze. Also, there are newer versions of the SDK (v1.1.0), could you please try again with latest packages?

**Comment by MadMax2410** [comment]
Thanks Zezha!

I've just fixed it replacing the html5lib folder.

Thanks!

**Comment by dxkaufman** [comment]
Hi @zezha-msft 

I am hoping you might be able to help me.  I am having similar problems on my Mac with Visual Studio Code.  I'm very new to this, and I don't entirely understand what is going on.  Here's what I can tell you:

I have VSC set to use ./env/bin/python:

![image](https://user-images.githubusercontent.com/26446314/56708047-2adf0380-66d0-11e9-9a9d-ff1736401e54.png)

When I run pip freeze in the terminal window, I see the following, among others, but I do not know for certain that is actually looking in the right place, as the terminal window isn't telling me that it is in the env.

azure==4.0.0
azure-common==1.1.18
azure-storage-blob==1.5.0
azure-storage-common==1.4.0
azure-storage-file==1.4.0
azure-storage-queue==1.4.0

If I look in ./env/lib/python3.6/site-packages, I see azure common and azure storage, although storage doesn't have a blob folder:

![image](https://user-images.githubusercontent.com/26446314/56708479-a2f9f900-66d1-11e9-9100-81e2a5926fc1.png)

When I set VSC to use the ./env/bin/python version, I get a lint error on the import statement "from azure.storage.blob import (BlockBlobService)":

![image](https://user-images.githubusercontent.com/26446314/56708532-d2a90100-66d1-11e9-91b2-2eba02832a20.png)

If I use either of the other two 3.6.5 versions, I don't get the error from lint.  Regardless of which I use, though, I do get the error in the terminal when I try to run the code:

[4/25/19 3:46:16 AM] System.Private.CoreLib: Exception while executing function: Functions.BlobTest. System.Private.CoreLib: Result: Failure
[4/25/19 3:46:16 AM] Exception: ModuleNotFoundError: No module named 'azure.storage.blob'

I'm sorry if some of this is pretty basic; as I said, I'm very new to most of this.  Until the last few weeks, it's probably been a decade since I wrote any code, and that was Java.

Thank you for any help you can give!
Dylan

**Comment by zezha-msft** [comment]
Hi @dxkaufman, no worries and thanks for reaching out!

It looks like your `pip freeze` was called on the global environment. You need to activate the virtual environment to see which package is installed, by running `source ./env/bin/activate`. Please refer to this guide for [more info](https://realpython.com/python-virtual-environments-a-primer/).

**Comment by dxkaufman** [comment]
Thanks, @zezha-msft.  You're exactly right.  I'd been trying to activate it, but forgetting the 'source' part.  Thanks for the link to that primer.  I will definitely read it before I try to set up an environment on my laptop as well... Now that my timer triggered function is done, though, I have to do an endpoint function to take webhook data from one of our cloud services...

**Comment by dxkaufman** [comment]
Hi @zezha-msft, 

I'm afraid I spoke too soon.  It now works fine when I run in VSC, but once I deploy to Azure, it fails:

2019-04-26T00:22:06.965 [Information] Executing 'Functions.DataPipeline' (Reason='This function was programmatically called via the host APIs.', Id=0612406c-f26f-40d8-987f-a1dc22d9ad78)
2019-04-26T00:22:07.031 [Error] Executed 'Functions.DataPipeline' (Failed, Id=0612406c-f26f-40d8-987f-a1dc22d9ad78)
Result: Failure
Exception: ModuleNotFoundError: No module named 'azure.storage'
Stack:   File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/functions_worker/dispatcher.py", line 218, in _handle__function_load_request
    func_request.metadata.entry_point)
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/functions_worker/loader.py", line 66, in load_function
    mod = importlib.import_module(fullmodname)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/site/wwwroot/DataPipeline/__init__.py", line 9, in <module>
    import azure.storage.blob as azureblob

For the short-term, I'm going to put my config JSON back into the code, but we really want to pick it up off the encrypted blob storage... 

Any suggestions?

Thanks,
Dylan

**Comment by zroozbehi** [comment]
Hi @zezha-msft

I am not sure if you had exactly the same issue as mine, but what solved my problem was that I realized you have to put all libraries you want in the requirment.txt with the right dictation!!!! I had two mistakes:
First, writing azure.storage.blob instead of azure-storage-blob in the requirment.txt
Then thinking that when I make an environment locally, after deployment all libraries must be copied on the cloud anyway, so I kept requirment.txt empty! 

But it doesn't work like that! Even the Python versions are not the same. I chose Python 3.8 when making the function app, for example. And then installed 3.8.0 on my local environment, because I though this bit I have to follow Azure(!), and Azure will follow my environment libraries. But then when I checked the Azure Python version it was 3.8.11!
So, the reality is that you don't have control on the exact version of the Azure Python. And about libraries, you only can put your requests in the requirment.txt. And Azure doesn't have anything to do with your local environment!
