### ISSUE TITLE
NewConnectionError from BlockBlobService.create_container

### ISSUE THREAD

**Issue by scobb** [Azure/azure-storage-python#287]
This is on Windows10, running python 2.7.10. Same code (and credentials) works on Ubuntu and CentOS running Python 3.5.2 with no problem. Issue is 100% reproduceable on affected storage/computer, but does seem to be system specific. I can provide credentials to affected storage/remote access to my system in Skype (stcob).

Stack Trace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\azure-cli\src\command_modules\azure-cli-ml\azure\cli\command_modules\ml\service\_realtimeutilities.py", line 49, in upload_dependency
    package_location = context.upload_dependency_to_azure_blob(dependency, az_container_name, az_blob_name)
  File "E:\azure-cli\src\command_modules\azure-cli-ml\azure\cli\command_modules\ml\_util.py", line 187, in upload_dependency_to_azure_blob
    bbs.create_container(container)
  File "c:\python27\lib\site-packages\azure\storage\blob\baseblobservice.py", line 596, in create_container
    self._perform_request(request)
  File "c:\python27\lib\site-packages\azure\storage\storageclient.py", line 270, in _perform_request
    raise ex
azure.common.AzureException: ConnectionError: HTTPSConnectionPool(host="'scwink8sstor'.blob.core.windows.net", port=443): Max retries exceeded with url: /amlbdpackages?restype=container (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0389D4F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

System info
E:\forked\amlbdcli>pip freeze | findstr mgmt-storage
azure-mgmt-storage==1.0.0rc1
E:\forked\amlbdcli>python
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32

**Comment by rambo-msft** [comment]
Hi scobb, I see you're using azure cli to perform this request, but to confirm the storage library does indeed support Python 2.7.10 on Windows 10. 

It seems this issue is related to your target machine actively refusing the connection.

> Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
This here suggests DNS, but the stacktrace can sometimes be misleading.

Several things I would try,
Update your `urllib` and `requests` library package,
Ping the host from that machine to ensure a system proxy or process is not interfering.

Requests does not cache DNS lookups, so this is suggestive of an issue related to Python or the OS.

**Comment by scobb** [comment]
Well, turns out this was user error. Windows was not stripping single quotes from environment variables the same way Linux does, so we ended up with a corrupted URL (host="'scwink8sstor'.blob.core.windows.net" from above). Thanks for your response, rambo!
