### ISSUE TITLE
Need document to use storage emulater

### ISSUE THREAD

**Issue by crwilcox** [Azure/azure-storage-python#3]
### Description:
This version document is no description to use local storage emulater.
Need some description that environment variable("EMULATED") and set None to account_name and account_key.

**Comment by jehine-MSFT** [comment]
Hello @ Philmist,

We acknowledge that our emulator support is not where we would like it to be right now but hope that by our next major release we can improve the support and documentation for all emulator scenarios.

Thanks for the feedback!

**Comment by jehine-MSFT** [comment]
Hello @Philmist,

We have improved the Azure Storage Emulator support for our python library in the 0.30 release. Now to enable emulator support, all the client needs to do is pass is_emulated=True when creating a Storage service object and all requests will be sent against the emulator instead of live storage. Please let us know if you have any trouble with our improved support.

Thanks again for the feedback!
