### ISSUE TITLE
File Methods throw exceptions that break remote debugging

### ISSUE THREAD

**Issue by crwilcox** [Azure/azure-storage-python#309]
When remote debugging an app I wrote that leverages the File APIs I found two unhandled exceptions that break debugging. These should be resolvable to be handled. This may need to be broken into two issues, but they are very similar issues both pertaining to, from what I can tell, passing requests an odd call.

## Call
directory_listing = self._files_service.list_directories_and_files('sharename', '')

### Exception:
{'message': "getresponse() got an unexpected keyword argument 'buffering'", 'exception_type': <class 'TypeError'>, 'exception': TypeError("getresponse() got an unexpected keyword argument 'buffering'",)}

### Call Stack:
 	get_auth_from_url in utils line 842	Python
 	prepare_auth in models line 531	Python
 	prepare in models line 309	Python
 	prepare_request in sessions line 431	Python
 	request in sessions line 488	Python
 	perform_request in httpclient line 114	Python
 	_perform_request in storageclient line 221	Python
 	_list_directories_and_files in fileservice line 1154	Python
 	list_directories_and_files in fileservice line 1106	Python

## Call
properties = self._files_service.get_file_properties('sharename', '', 'file.txt').properties

### Exception: 
{'message': "argument of type 'NoneType' is not iterable", 'exception_type': <class 'TypeError'>, 'exception': TypeError("argument of type 'NoneType' is not iterable",)}

### Call Stack:  
 	get_auth_from_url in utils line 842	Python
 	prepare_auth in models line 531	Python
 	prepare in models line 309	Python
 	prepare_request in sessions line 431	Python
 	request in sessions line 488	Python
 	perform_request in httpclient line 114	Python
 	_perform_request in storageclient line 221	Python
 	get_file_properties in fileservice line 1181	Python

**Comment by zezha-msft** [comment]
Hi @crwilcox, I apologize for the delayed response, I've been sick lately😿 .

Unfortunately I do not think I can do much to help with your situation, as this kind of first chance exceptions happen inside the `requests` module, and I have no control over that. In addition, it is very likely that your error message `"argument of type 'NoneType' is not iterable"` is not the actual error, please take a look at this [issue](https://github.com/requests/requests/issues/1915#issuecomment-287003675) from the `requests` repo. My guess is that you had a connection error of some sort.

I would suggest you to explore the possibility of configuring your tool so that it does not break for first chance exceptions. As far as I can tell, we are not passing anything unusual to the `requests` module.

Please let me know if I missed anything or if you have any question. Thanks!
