### ISSUE TITLE
Ability to avoid reusing connections as an option

### ISSUE THREAD

**Issue by eligne-pro** [Azure/azure-storage-python#312]
We are using azure storage module from python code executed from AzureML experiments, to store and retrieve data in an external container.
Access through HTTP with the lib is ok, but when switching to HTTPS it times out.
Microsoft people who support us have quoted the following:

> 'Python libraries using HTTPS generally don’t work well in the Execute Python Script module because our security sandbox. Azure-storage SDK is probably not going to work for you if you want HTTPS.'

and
'

> Yes exactly, to clarify the issue, the known issue with the sandbox and secure connections is the reuse of secure connections

'

We are able to use HTTPS from the sandbox for REST WebService calls through requests module, so HTTPS itself passes through. Redeveloping the PUT part of Blob storage client using requests seems heavy. Could it be possible to parameterize the BlobService(s) to enter a mode compatible with the security sandbox (meaning: no reuse of HTTPS connections)?

**Comment by zezha-msft** [comment]
Hi @eligne-pro, each time you create a service (i.e. BlockBlobService), we keep using the same [requests.Session](http://docs.python-requests.org/en/master/api/#request-sessions) object to make the requests, since Session takes care of connection pooling and also allows the reusing of the underlying TCP connections to the same host. This is great for [performance](http://docs.python-requests.org/en/master/user/advanced/#session-objects), and makes sense in most scenarios, but unfortunately except in your case. 

Since we already use the `requests` module, and our library is open-source, it would actually be really easy to make the change that you are suggesting. Basically, you need to change [this part](https://github.com/Azure/azure-storage-python/blob/master/azure/storage/_http/httpclient.py#L108) to not use the Session object. So you could build your own version of this library for the specific scenario that you are encountering.

I will raise your suggestion with my colleagues, but cannot promise anything.

Please let me know if you have any question. 😃

**Comment by eligne-pro** [comment]
Hi @zezha-msft , thank you so much for your answer.

I did try to do what you describe and changed the pointed line to 
`        # Send the request
        response = requests.request(request.method, 
instead of using the session.

This does not work neither in the AzureML context.
Do you confirm that, if the problem were due to connection reuse, this 'patch' should solve it? (meaning: the timeout observed in my situation is not due to this ?) or did I miss something and patched wrongly?

Thanks for any indication.

**Comment by zezha-msft** [comment]
@eligne-pro As far as I can tell from reading the `requests` [doc](http://docs.python-requests.org/en/master/user/advanced/#keep-alive), not using Session should solve your problem. However, since I have no knowledge of AzureML, I cannot confirm anything for you unfortunately. You could also try to set the `keep_alive` option to false as suggested [here](https://stackoverflow.com/questions/10115126/python-requests-close-http-connection), and see if that helps with your situation.

To be clear, I would definitely suggest you **to keep using HTTP until AzureML fixes this issue**. It is extremely strange that a security sandbox doesn't play nice with HTTPS. I have discussed your suggestion with my colleagues and unfortunately we do not think it is on us to make this fix, I suggest that you escalate this with AzureML and see if they can fix the issue at the source.

With that being said, I did come across a potential workaround for your situation. Feel free to try this, but I cannot promise it will work. 😿  I hope this helps.

Step1:
sess = requests.Session()
adapter = requests.adapters.HTTPAdapter(pool_connections=0, pool_maxsize=0)
sess.mount('https://', adapter)
table_service = TableService(account_name='AccountName', account_key='AccountKey', protocol="http", request_session=sess)

Step2: monkey patch requests' bundled urllib3
**Connectionpool.py [new, then original]:**
```python
def _get_conn(self, timeout=None):
        """
        Get a connection. Will return a pooled connection if one is available.

        If no connections are available and :prop:`.block` is ``False``, then a
        fresh connection is returned.

        :param timeout:
            Seconds to wait before giving up and raising
            :class:`urllib3.exceptions.EmptyPoolError` if the pool is empty and
            :prop:`.block` is ``True``.
        """
        conn = None
        print('Using AKs new poolmanager')
        # If this is a persistent connection, check if it got disconnected
        if conn and is_connection_dropped(conn):
            log.info("Resetting dropped connection: %s" % self.host)
            conn.close()
            if getattr(conn, 'auto_open', 1) == 0:
                # This is a proxied connection that has been mutated by
                # httplib._tunnel() and cannot be reused (since it would
                # attempt to bypass the proxy)
                conn = None

        return conn or self._new_conn()

def _get_conn(self, timeout=None):
        """
        Get a connection. Will return a pooled connection if one is available.

        If no connections are available and :prop:`.block` is ``False``, then a
        fresh connection is returned.

        :param timeout:
            Seconds to wait before giving up and raising
            :class:`urllib3.exceptions.EmptyPoolError` if the pool is empty and
            :prop:`.block` is ``True``.
        """
        conn = None
        try:
            conn = self.pool.get(block=self.block, timeout=timeout)

        except AttributeError:  # self.pool is None
            raise ClosedPoolError(self, "Pool is closed.")

        except Empty:
            if self.block:
                raise EmptyPoolError(self,
                                     "Pool reached maximum size and no more "
                                     "connections are allowed.")
            pass  # Oh well, we'll create a new connection then

        # If this is a persistent connection, check if it got disconnected
        if conn and is_connection_dropped(conn):
            log.info("Resetting dropped connection: %s" % self.host)
            conn.close()
            if getattr(conn, 'auto_open', 1) == 0:
                # This is a proxied connection that has been mutated by
                # httplib._tunnel() and cannot be reused (since it would
                # attempt to bypass the proxy)
                conn = None

        return conn or self._new_conn()
```
