### ISSUE TITLE
Retry callback should provide exception context

### ISSUE THREAD

**Issue by alfpark** [Azure/azure-storage-python#363]
The retry handling logic should provide the **unwrapped** exception context (i.e., the exception that `AzureException` wraps) to the `retry_callback()`. Please see the [affected code](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-common/azure/storage/common/storageclient.py#L343).

There does not seem to be a good reason to suppress this information from custom retry handlers and obfuscates why a retry is being called (and thus why an exception was raised for the request). Simply discerning that a `context.response` of `None` as [**always** needing a retry is arbitrary](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-common/azure/storage/common/retry.py#L60-L65) and does not apply to all situations. For example, a connection fault (i.e., Exception) from the lower layer urllib3 of `[Errno -2] Name or service not known` should not be retried, but will always be retried with no way to change this behavior without providing a `try/except` around the actual storage SDK call itself. Doing so would defeat the purpose of custom retry handlers wrapping this type of functionality.

The proposal is to either add the exception context on the `RetryContext` or add an optional parameter to the `retry_callback` function. The former would be a cleaner approach.

**Comment by zezha-msft** [comment]
Hi @alfpark, thanks for bringing up the issue. I have added an item in our backlog to provide the exception on RetryContext.

If I'm understanding your situation correctly, you want to implement your own retry class, right? Because retry_callback does not arbitrate whether a retry is supposed to happen, its job, according to the documentation, is to simply "detect retries and log context information". So if you want to avoid retries in certain situations (like the urllib3 error you mentioned), you'll need to implement your own retry class/method used [here](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-common/azure/storage/common/storageclient.py#L339).

**Comment by alfpark** [comment]
Yes, I currently have my own custom retry class, but since the `RetryContext` being passed does not contain the exception context and it's not passed into the callback itself, there's no way for any custom handler to make a determination of what to correctly do during `context.reponse is None`.

Adding a reference to the unwrapped exception as a member of `RetryContext` would be great.

**Comment by zezha-msft** [comment]
@alfpark This was fixed in azure-storage-common v0.37.1.
