### ISSUE TITLE
How to download publicly available objects from blob storage? 

### ISSUE THREAD

**Issue by apengwin** [Azure/azure-storage-python#375]
I have some files in blob storage that I want publicly available, but I"m unsure of how someone would fetch them.

It looks like the [`azure.storage.common.storageclient module`](https://azure-storage.readthedocs.io/en/latest/ref/azure.storage.common.storageclient.html) is the right way to go, but It's unclear how to use this.

**Comment by zezha-msft** [comment]
Hi @apengwin, please start by reading the [tutorial](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-python-how-to-use-blob-storage). 

storageclient is not the way to go, please take a look at the [sample](https://github.com/Azure/azure-storage-python/blob/master/samples/blob/sas_usage.py#L55).

**Comment by apengwin** [comment]
@zezha-msft  I'm confused by how container names are uniquely identified. I currently have two separate accounts each with a blob container called `azure-webjob-hosts`, and am unsure how 
 `block_blob_service.get_blob_to_path(azure-webjob-hosts, 'myblockblob', 'out-sunset.png')` would get resolved.

**Comment by zezha-msft** [comment]
Hi @apengwin, when you create a BlockBlobService, you have to specify your storage account. Account name + container name is a unique identifier for containers. These concepts are all explained in the [tutorial](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-python-how-to-use-blob-storage) that I linked to previously.

**Comment by apengwin** [comment]
@zezha-msft I understand that the storage account name and container name are a unique identifier for each container, but the docs actually aren't clear about that, or what that means.

Explicitly, I have an account with name `foo` and container `container1`, which is public.

I'm trying to access it with account `bar`, so I'm guessing something like

```
block_blob_service = BlockBlobService(account_name='bar', account_key='bar_key')
block_blob_service.get_blob_to_path( what_do_i_put_for_container_name_here, blob_i_want, local_path)
```
How do specify the container name/ is it `foo/container1`? or `foocontainer1`?

**Comment by richardliaw** [comment]
The sample code linked above is very unclear. 

The proper way to do this is given that you've published a container `azure-webjob-hosts` with account name`foo`, you would call - 
```
bar_bbs = BlockBlobService(account_name='bar', account_key=None)
bar_bbs.get_blob_to_path(azure-webjob-hosts, blob_i_want, local_path)
```

I hope that helps, @apengwin.

It would be nice to have better sample code for future reference.

**Comment by apengwin** [comment]
Thanks @richardliaw!

**Comment by zezha-msft** [comment]
Hi @richardliaw, thanks for the help, but that is not right at all. Like the [sample](https://github.com/Azure/azure-storage-python/blob/master/samples/blob/sas_usage.py#L67) shows, When you create a BlockBlobService, you specify the account name that owns the container. In this case, you want to access the container `azure-webjob-hosts` on account `foo`, so you should do this:

```python
anonymous_service = BlockBlobService('foo')
anonymous_service.get_blob_to_path('azure-webjob-hosts', 'blob_name', local_path)
```

@apengwin Accessing the public blob has nothing to do with the account 'bar', because the container is not owned by 'bar'. As the tutorial explains, each blob can be thought of as a resource, and can be access with an url like this `https://storagesample.blob.core.windows.net/mycontainer/blob1.txt`. `storagesample` is the account name, `mycontainer` is the container name, and `blob1.txt` is the blob name.

Please let me know if you have any other question.

**Comment by richardliaw** [comment]
ah sorry, edited above. thanks for the catch.
