### ISSUE TITLE
Partial download reported as success in SDK API get_blob_to_path()

### ISSUE THREAD

**Issue by reeshabhraj1** [Azure/azure-storage-python#434]
### Which service(blob, file, queue) does this issue concern?
We are downloading the Azure blob using Azure python SDK with API get_blob_to_path(). API reports success, however data downloaded is partial.

### What problem was encountered?
Below is the code snippet
Note: This is the custom code snipet. The main code is the call to the SDK API get_blob_to_path() in below sample.

```
def download_file(self, f_context):
      src_file_path = f_context.src_path
      dest_file_path = f_context.dest_path
      az_uri = AzureUri(src_file_path)
      kek = self._blob_service.key_encryption_key
      require_encryption = self._blob_service.require_encryption
      self._blob_service.key_encryption_key = None
      self._blob_service.require_encryption = False
      try:
          blob = self._blob_service.get_blob_to_path(container_name=az_uri.container(),
                                                    blob_name=az_uri.blob_path(),
                                                    file_path=dest_file_path,
                                                    timeout=self.op_timeout)
          props = blob.properties
          self.logger.debug('download_file content_length:%s. content_range:%s', props.content_length, props.content_range)
          self.logger.debug('download_file file size:%d', os.path.getsize(dest_file_path))
      except Exception as err:
          self.logger.error('download_file failure. Error:%s \\n StackTrace:{%s}', str(err), traceback.format_exc())
          raise
      finally:
          self._blob_service.key_encryption_key = kek
          self._blob_service.require_encryption = require_encryption
```

Below are logs from above code path
```
10294: 2018-01-25 11:04:15,503 - DEBUG - lib.ms_azure.azure_file_handler:download_file - download_file content_length:171490. content_range:bytes 0-171489/171490
10294: 2018-01-25 11:04:15,504 - DEBUG - lib.ms_azure.azure_file_handler:download_file - download_file file size:48588
```

Below are analytic logs with removed account specific details:
`1.0;2018-01-25T05:33:36.3654235Z;GetBlob;NetworkError;206;38480;20;authenticated;xxxxxx....`

Question:
Actual blob content length is :171490
As indicated by the analytic logs, request returned 206 (partial content)
However python SDK API get_blob_to_path() reported success

Only partial data is getting downloaded while SDK returns success. This results in data corruption at our side.

Expectations:
When using SDK API get_blob_to_path(), to request complete blob:

SDK API returns complete blob i.e. all the data of the blob is returned.
SDK API fails i.e. it throws exception regardless of what led to underlying behaviour (network error or any other transient issue).

**Comment by zezha-msft** [comment]
Hi @reeshabhraj1, [206](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/206) is the [expected response](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob#status-code), since we are doing a ranged GET.

I was not able to reproduce your problem with a blob of exactly 171490 bytes. Could you please reproduce it again and verify (with a different method) if the file size is indeed 48588 bytes? Is there anything else that is also manipulating dest_file_path?

It is very unlikely that the size discrepancy was caused by the storage SDK, as this is a very basic use case and we have plenty of tests that cover it. 

Thank you!

**Comment by seguler** [comment]
We discussed this today. During a download, if a network error happens, underlying libcurl library will throw and be propagated to the Python SDK to the client. 

In your test however, it seems the TCP stack is succeeding since you are manipulating the body with fiddler successfully hence there is no error thrown and propagated to the Client. This is the issue here. The test does not really simulate a real life scenario failure.

**Comment by zezha-msft** [comment]
Hi @reeshabhraj1, I was able to reproduce your test case with the extra info provided by the support team. We indeed do not validate the consistency between content-length and content-range, because that is guaranteed by the service. 

Another thing I wanted to clarify is: when the SDK ask the service for a range of data, and that range is valid, then the service will always provide the entirety of that data. For example, your blob has 171490 bytes; if we ask the service for the range 0-171489, then the service always returns 171490 bytes. If the connection breaks for some reason in the middle, the call will be retried.

I'm a bit curious about why you are simulating this failure from the Storage service, could you please provide some insights?

Thanks!

**Comment by zezha-msft** [comment]
Hi @reeshabhraj1, I tried reproducing your scenario by downloading a larger blob (100MB) with get_blob_to_path and MAX_SINGLE_GET_SIZE set to 200MB, so it's still a single get. Then in the middle of the download, I turned off my network adapter, thus imitating a network failure. From the logs I see that the SDK gets a read timeout and performs retries. After all retries were exhausted, an exception was thrown. Thus I was not able to reproduce this situation that you encountered.

Could you please try to reproduce this problem in a more isolated way? Which version of the SDK are you using?

Thanks!

**Comment by reeshabhraj1** [comment]
I agree this is the expected behaviour but this was not the behaviour that
was observed by us. We observed that a network blip caused 206 partial
content being returned as confirmed by the analytic logs and that being
reported as success by the SDK. This may be due to partial content returned
on a single chunk but we saw no retries in our case.

Analytic logs observed by us :

> 1.0;2018-01-25T05:33:36.3654235Z;GetBlob;NetworkError;
> 206;38480;20;authenticated;xxxxxxx...


Our logs:

> 10294: 2018-01-25 11:04:15,503 - DEBUG - lib.ms_azure.azure_file_handler:download_file
> - download_file content_length:171490. content_range:bytes 0-171489/171490
> 10294: 2018-01-25 11:04:15,504 - DEBUG - lib.ms_azure.azure_file_handler:download_file
> - download_file file size:48588




We have also not been able to reproduce the network blip as it is not
possible for us to turn network connection off for one VM in our data
center.


Regards,
Reeshabh Raj

**Comment by zezha-msft** [comment]
Hi @reeshabhraj1, did you enable [logging](https://github.com/Azure/azure-storage-python#logging) from the SDK when the error happened? It would really be helpful to look at the SDK logs. Thanks!

**Comment by zezha-msft** [comment]
Hi @reeshabhraj1, could you please provide the logs for when the error happened?

**Comment by reeshabhraj1** [comment]
I had already shared all the logs i had. The azure analytic logs as well as our application logs regarding difference in size of downloaded file and requested file. Both the logs can be found above in the origin issue description. We will enable logging from Azure SDK but this problem has not occurred again so nothing to share from there..

**Comment by reeshabhraj1** [comment]
Not able to repro. Closing the issue.
