### ISSUE TITLE
Recommendation: consider removing class to time.sleep

### ISSUE THREAD

**Issue by RobertoPrevato** [Azure/azure-storage-python#445]
Hello,
as some of you may know, in the last weeks I've been working on an unofficial fork of Azure Storage Python SDK to support `asyncio` and asynchronous web requests. I created [this fork](https://github.com/RobertoPrevato/azure-storage-python) for personal interest and I am using it successfully to connect to Blob, Table and Queue services using asynchronous web requests and `aiohttp` framework.

While making it, I found a place of the code that might cause performance issues in the official Python SDK: the use of `time.sleep` when retry policy enables retries to any Storage api inside `storageclient.py`.
Here: [lines 345, 346](https://github.com/Azure/azure-storage-python/blob/19d845d58551bd36a04c46628dc42089ee269362/azure-storage-common/azure/storage/common/storageclient.py)

```py
                    # Sleep for the desired retry interval
                    sleep(retry_interval)
```

### Which service(blob, file, queue) does this issue concern?
All services.

### What problem was encountered?
This is not a bug, but using `time.sleep` when retry policy enables retries makes the Azure Storage Python SDK potentially not suitable for production web applications. For example, I think that developers working on the official .NET Storage SDK would not tolerate having calls to **[System.Threading.Thread.Sleep](https://msdn.microsoft.com/en-us/library/d00bd51t(v=vs.110).aspx)**, as this is generally considered a bad practice, since it blocks code execution for a whole thread.

### Have you found a mitigation/solution?
Yes, one solution would be migrating to `asyncio` and using `asyncio.sleep`. asyncio.sleep can be seen as functionally equivalent to .NET [System.Threading.Tasks.Task.Delay](https://msdn.microsoft.com/en-us/library/hh194845(v=vs.110).aspx), thus an efficient way to wait without blocking code execution. It seems there are also other solutions in Python `threading` module, but I don't have experience with them.

### Note:
I don't want to be pedantic, I just want to give a friendly recommendation. :beer:

**Comment by zezha-msft** [comment]
Hi @RobertoPrevato, thanks for reaching out! Design discussions are always welcome. 😄 

The usage of `time.sleep` was very much intentional, as we want to make sure the thread is suspended while we wait for the next try. I believe it is a fairly normal thing to do in a synchronous programming model. In addition, the user can specify a different retry policy to shorten the time to wait(even to 0 if needed) if they feel like it is not the behavior they desired. Please share your thoughts if you think there is a better way of doing this!

I do agree that the asynchronous programming model is far superior in terms of efficiency, and that is why we will break ground on the official async version of the SDK later this year. It will feature a new design similar to the [new Go SDK](https://github.com/Azure/azure-storage-blob-go), and use Swagger generated protocol code.

**Comment by RobertoPrevato** [comment]
Hi @zezha-msft, thanks for your answer! :)

Since you are working on the async SDK, then the thing I described will go away immediately.

Thanks, have a great day!
