### ISSUE TITLE
Blob upload is failing for Azure Government

### ISSUE THREAD

**Issue by prburgu** [Azure/azure-storage-python#471]
### Which service(blob, file, queue) does this issue concern?
Blob

### What problem was encountered?

It appears that the REST version has been changed to 2018-03-28 with the latest SDK, however it appears this version is not available in Azure Government yet. Also, I couldn't find a way to use particular REST version with the Blob Service and always takes the default.

```
azure.common.AzureHttpError: The value for one of the HTTP headers is not in the correct format.
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.
RequestId:83003cd7-d01e-0006-2d16-138904000000
Time:2018-07-03T21:40:55.6040097Z</Message><HeaderName>x-ms-version</HeaderName><HeaderValue>2018-03-28</HeaderValue></Error>
```
### Have you found a mitigation/solution?
Pinning to following versions works
```
azure-storage-blob~=1.2.0rc1
azure-storage-common~=1.2.0rc1
```

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by zezha-msft** [comment]
Hi @prburgu, thanks for reaching out!

We pin each SDK release to a specific service version, because this way we can guarantee the SDK's behavior by testing it thoroughly. In addition, there are often new APIs that do not work with the previous service versions. 

The Azure Government regions will eventually get the new 2018-03-28 service version. In the mean time, please use the previous versions of the SDK. 

Alternatively, you could edit this [line](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-blob/azure/storage/blob/_constants.py#L11) and install 1.3.0 from source. However, you won't be able to use the new features such as get account info and put block from URL.
