### ISSUE TITLE
Unclear api import for QueueService

### ISSUE THREAD

**Issue by EricSchles** [Azure/azure-storage-python#472]
### Which service(blob, file, queue) does this issue concern?

queue

### What problem was encountered?
```
>>> from azure.storage.queue.queueservice import QueueService
>>> from azure.storage.queue import QueueService
```
Both work, this is potentially confusing.  Perhaps we can standardize around one and only one way to import QueueService

### Have you found a mitigation/solution?

Not as of yet.

**Comment by zezha-msft** [comment]
Hi @EricSchles, thanks for reaching out!

What you described is the expected behavior. You can always import QueueService from the file in which it was defined:
```
from azure.storage.queue.queueservice import QueueService
```

However, the users of the SDK should not have to know which file contained what, so we [made sure that the necessary classes can be more easily imported like so:](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-queue/azure/storage/queue/__init__.py)
```
from azure.storage.queue import QueueService
```

I believe this is a well-known pattern in Python, the azure-sdk-for-python also does the [same thing](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-servicebus/azure/servicebus/__init__.py).
