### ISSUE TITLE
Can python api for AzureFile support to upload local directory to remote?

### ISSUE THREAD

**Issue by Cherishty** [Azure/azure-storage-python#482]
### Which service(blob, file, queue) does this issue concern?
Azure File

### Which version of the SDK was used? Please provide the output of `pip freeze`.
azure-storage-common==1.3.0
azure-storage-file==1.3.1
azure-storage-nspkg==3.0.0

### What problem was encountered?
Can python api for AzureFile support to upload a local directory to remote?
downloading folder is the same requirement
If not, why?
I was using web_hdfs python api which support this behavior

### Have you found a mitigation/solution?
If this function is not provided by api , we may recursively invoke **create_file_from_path()** by folder's hierarchy, but I believe it is too strange

**Comment by zezha-msft** [comment]
Hi @Cherishty, thanks for reaching out!

I understand that you have a need for uploading/downloading entire directories, but I do not believe the SDK is the right place for that functionality. This is because the SDK is only supposed to be a thin wrapper over the [REST API](https://docs.microsoft.com/en-us/rest/api/storageservices/file-service-rest-api), so the user should be responsible for enumerating the directory and making the decisions about the behavior(ex: whether or not to follow symbolic links). Listing directories should be [straightforward](https://stackoverflow.com/questions/3207219/how-do-i-list-all-files-of-a-directory).

If you would like to use a tool to upload/download directories, please consider [AzCopy](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy), or the experimental [AzCopy V2](https://github.com/Azure/azure-storage-azcopy). Here is a [guide](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy#upload-files-to-an-azure-file-share).

**Comment by zezha-msft** [comment]
Hi @Cherishty, I agree that a batch SDK could be useful to customers. We currently have this item on our backlog but unfortunately have no timeline yet. Thanks!
