### ISSUE TITLE
[ParentNotFound] Azure File SDK can NOT create_directory recursively

### ISSUE THREAD

**Issue by Cherishty** [Azure/azure-storage-python#483]
### Which service(blob, file, queue) does this issue concern?
Azure File

### Which version of the SDK was used? Please provide the output of `pip freeze`.
azure-storage-common==1.3.0
azure-storage-file==1.3.1
azure-storage-nspkg==3.0.0

### What problem was encountered?
When running `file_service.create_directory(__share_name,  "root_path/leaf_path")`, if **root_path** is not existed, an exception that "ParentNotFound" will throw.
No override method is provided for recursive create dir like "mkdir -p" ?

**Comment by zezha-msft** [comment]
Hi @Cherishty, recursively creating directories is not supported by the [REST API](https://docs.microsoft.com/en-us/rest/api/storageservices/create-directory) unfortunately. 

We did not add such overload in the SDK because each IO to the Storage Service incurs a cost, so the customer should consciously make each call.
