### ISSUE TITLE
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

### ISSUE THREAD

**Issue by wyblzu** [Azure/azure-storage-python#487]
### Have you found a mitigation/solution?

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by zezha-msft** [comment]
Hi @wyblzu, it looks like your authentication is not working. Please make sure that you put the right storage account name and key, if you are using shared key to authenticate against the Storage service. If you are using a SAS token, please double-check that it is still valid. 

If it is your first time using a Storage SDK, please take a look at the [quick start for python](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python).

I'm closing this since it does not seem to be a problem in the SDK. Please answer the template questions if you would like to report an issue. Thanks!
