### ISSUE TITLE
(Suggestion) Cannot directly install the package in Apline Docker. 

### ISSUE THREAD

**Issue by G-K-Patel** [Azure/azure-storage-python#496]
### Which service(blob, file, queue) does this issue concern?
Blob

### Which version of the SDK was used? Please provide the output of `pip freeze`.
azure-storage==0.36.0

### What problem was encountered?
I tried to do "RUN venv/bin/pip install azure-storage" in an Alpine Docker, but this gave multiple errors. Possibly because SSL and other libraries are required. Please check my solution (below) and give me your comments. And maybe, the installation of the below mentioned packages can be automated (just a suggestion). 

### Have you found a mitigation/solution?
I found out that, some more dependencies were required, as follows:
RUN apk add --no-cache --virtual .pynacl_deps build-base python3-dev libffi-dev openssl-dev

**Comment by zezha-msft** [comment]
Hi @mukt-muni, thanks for reaching out!

I see that you are using an outdated version of the SDK, could you please update to the latest version? There have been numerous bug fixes and improvements since 0.36.0. In addition, the SDK has split into separate packages for each service, ex: azure-storage-blob, azure-storage-queue, etc.

For the install issue, could you please quickly check whether you can install the dependencies individually? The [3 main dependencies](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-common/setup.py#L77) are:

- 'cryptography',
- 'python-dateutil'
- 'requests'

**Comment by zezha-msft** [comment]
I strongly suspect that your issue was related to the `cryptography` package, and not the Storage SDK itself. Please take a look at this [article](https://cryptography.io/en/latest/faq/#cryptography-failed-to-install) if you still encounter this issue.

**Comment by zezha-msft** [comment]
Closing due to lack of response.

**Comment by zezha-msft** [comment]
Hi @G-K-Patel, thanks for getting back to me! If you don't mind, could you please share what you did to make your system work?

It doesn't sounds like the problem was related to our SDK, but it would nice for people who stumble upon this issue to see how you solved the problem. Thanks!

**Comment by G-K-Patel** [comment]
Hey, I posted a solution in my first post. This solution worked out for me. But, I dont know if its the best solution, you are the expert, maybe you can comment. Thanks.
