### ISSUE TITLE
Take long time to get the blob content from get_blob_to_stream and get_blob_to_text

### ISSUE THREAD

**Issue by TomFang123** [Azure/azure-storage-python#497]
### Which service(blob, file, queue) does this issue concern?
baseblobservice.py

### Which version of the SDK was used? Please provide the output of `pip freeze`.
azure_storage==0.36.0

### What problem was encountered?
We are using **get_blob_to_stream** and **get_blob_to_text** from **baseblobservice** to get the blob content, it normally take 20 secs around, and the blob content size is less than 7MB. This time is too long for us since we are getting data at runtime, which will impact our responsiveness to frontend

### Have you found a mitigation/solution?
we didn't find solution

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by zezha-msft** [comment]
Hi @TomFang123, thanks for reaching out!

I see that you are using an outdated version the SDK, could you please update to the latest version? There have been numerous important bug fixes and improvements since 0.36.0. 

Concerning the performance issue, I suggest to increase the parallelism of the download call, there are two steps in doing so:

1. get_blob_to_stream performs an initial get call(governed by `MAX_SINGLE_GET_SIZE` on the service object, which by default is 32MB) to retrieve some data but most important get the size of blob so that it can parallelize the download. Since your blob is much smaller than the default 32MB, there is no parallelism involved and the entire content is downloaded serially in the initial call. Therefore, you could start by changing MAX_SINGLE_GET_SIZE to something smaller.
2. In addition, once the size of the blob is known, the download operation will be parallelized according to the function parameter `max_connections`, which by default is 2. The size of each chunk is governed by MAX_CHUNK_GET_SIZE on the service object, so I would suggest to decrease this number as well to fit your scenario.

In general, the SDK's default values are geared towards larger blobs, so please feel free to change them so that it fits your specific scenario.

**Comment by TomFang123** [comment]
@zezha-msft 
thanks for your reply,
there are two things still not clear, firstly, how can we config "MAX_SINGLE_GET_SIZE ", 
1. "MAX_CHUNK_GET_SIZE ", looks like class didn't expose any interface which we can config (only if we directly change the code in library?)
2. we check the library, which 0.36 is latest version, can you provide the latest version no.?

**Comment by zezha-msft** [comment]
Hi @TomFang123, please refer to the [README](https://github.com/Azure/azure-storage-python#download) on how to install the latest packages. We are at version 1.3.1 for the blob package. 

As for the constants, you can simply set their values on the instantiated service object, like [here](https://github.com/Azure/azure-storage-python/blob/master/tests/blob/test_get_blob.py#L51).

Please let me know if you have any other question.
