### ISSUE TITLE
Installing the storage libraries on Linux fails

### ISSUE THREAD

**Issue by toddysm** [Azure/azure-storage-python#51]
Installing the storage libraries on Linux fails because __init__.py files for some packages cannot be found (see output below). One issue can be that there are some Windows-type new lines left in the file and those cannot be recognized on Linux. The same libraries work on Windows.

atvmadmin@atvmlnx03:~$ sudo easy_install3 azure-storage
Searching for azure-storage
Reading https://pypi.python.org/simple/azure-storage/
Best match: azure-storage 0.20.2
Downloading https://pypi.python.org/packages/source/a/azure-storage/azure-storage-0.20.2.zip#md5=19266cb50c9e6f31a463ca0909e0cc5a
Processing azure-storage-0.20.2.zip
Writing /tmp/easy_install-w41be_ss/azure-storage-0.20.2/setup.cfg
Running azure-storage-0.20.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-w41be_ss/azure-storage-0.20.2/egg-dist-tmp-v8dun7lk
**package init file 'azure/__init__.py' not found (or not a regular file)**
**warning: no previously-included files found matching 'azure/__init__.py'**
Adding azure-storage 0.20.2 to easy-install.pth file

Installed /usr/local/lib/python3.4/dist-packages/azure_storage-0.20.2-py3.4.egg
Processing dependencies for azure-storage
Searching for python-dateutil
Reading https://pypi.python.org/simple/python-dateutil/
Reading http://labix.org/python-dateutil
Reading https://dateutil.readthedocs.org
Best match: python-dateutil 2.4.2
Downloading https://pypi.python.org/packages/source/p/python-dateutil/python-dateutil-2.4.2.tar.gz#md5=4ef68e1c485b09e9f034e10473e5add2
Processing python-dateutil-2.4.2.tar.gz
Writing /tmp/easy_install-_xbk2zb_/python-dateutil-2.4.2/setup.cfg
Running python-dateutil-2.4.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-_xbk2zb_/python-dateutil-2.4.2/egg-dist-tmp-ugpjir_o
Adding python-dateutil 2.4.2 to easy-install.pth file

Installed /usr/local/lib/python3.4/dist-packages/python_dateutil-2.4.2-py3.4.egg
Searching for azure-common
Reading https://pypi.python.org/simple/azure-common/
Best match: azure-common 1.0.0
Downloading https://pypi.python.org/packages/source/a/azure-common/azure-common-1.0.0.zip#md5=936f523f8f0e11780fc0b8a87d56d390
Processing azure-common-1.0.0.zip
Writing /tmp/easy_install-khjsvnqk/azure-common-1.0.0/setup.cfg
Running azure-common-1.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-khjsvnqk/azure-common-1.0.0/egg-dist-tmp-843ee6_p
**package init file 'azure/__init__.py' not found (or not a regular file)**
**warning: no previously-included files found matching 'azure/__init__.py'**
Adding azure-common 1.0.0 to easy-install.pth file

Installed /usr/local/lib/python3.4/dist-packages/azure_common-1.0.0-py3.4.egg
Searching for azure-nspkg
Reading https://pypi.python.org/simple/azure-nspkg/
Best match: azure-nspkg 1.0.0
Downloading https://pypi.python.org/packages/source/a/azure-nspkg/azure-nspkg-1.0.0.zip#md5=cb046beb44c3efdb8bf1688af6c011ca
Processing azure-nspkg-1.0.0.zip
Writing /tmp/easy_install-iq0amqy_/azure-nspkg-1.0.0/setup.cfg
Running azure-nspkg-1.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-iq0amqy_/azure-nspkg-1.0.0/egg-dist-tmp-4s2vd4bg
Adding azure-nspkg 1.0.0 to easy-install.pth file

Installed /usr/local/lib/python3.4/dist-packages/azure_nspkg-1.0.0-py3.4.egg
Searching for six>=1.5
Reading https://pypi.python.org/simple/six/
Best match: six 1.10.0
Downloading https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz#md5=34eed507548117b2ab523ab14b2f8b55
Processing six-1.10.0.tar.gz
Writing /tmp/easy_install-o2cza5g_/six-1.10.0/setup.cfg
Running six-1.10.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-o2cza5g_/six-1.10.0/egg-dist-tmp-in03ps3n
no previously-included directories found matching 'documentation/_build'
zip_safe flag not set; analyzing archive contents...
__pycache__.six.cpython-34: module references __path__
Adding six 1.10.0 to easy-install.pth file

Installed /usr/local/lib/python3.4/dist-packages/six-1.10.0-py3.4.egg
Finished processing dependencies for azure-storage
atvmadmin@atvmlnx03:~$ python3
Python 3.4.0 (default, Jun 19 2015, 14:20:21)
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import azure.common
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'azure.common'
>>> import azure.storage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'azure.storage'

**Comment by toddysm** [comment]
Update: the install seems to be failing on Windows also.

**Comment by emgerner-msft** [comment]
This is an easy_install issue. If you check out our Readme file, we recommend using pip which we test with each time we release. Could you please try using pip on either OS, preferably in a virtual env in addition to the regular route?

**Comment by johnpneumann** [comment]
This is the same issue that I reported here #35 that got closed (I didn't respond and then locked in to the older version since it worked).

This isn't an easy_install issue, it's a packaging issue with how this package has been split up. In the previous issues response I was told:

> python setup.py doesn't install dependencies for you Look at setup.py and manually pip install each requirement dependency

Per the [setuptools docs](https://pythonhosted.org/setuptools/setuptools.html#declaring-dependencies)

>setuptools supports automatically installing dependencies when a package is installed, and including information about dependencies in Python Eggs (so that package management tools like EasyInstall can use the information).

By requiring users to use `pip` to install the packages that are in `install_requires` it means that we have to create workarounds to utilize the library here. It also means that I can't specify `azure-storage` in my setup.py's `install_requires` because it's not resolving the dependencies correctly. 

Here is a barebones example.
```
# setup.py
from setuptools import setup, find_packages

setup(
    name='azurepoc',
    version='0.0.1',
    packages=find_packages(),
    install_requires=[
        'azure-storage'
    ]
)
```

After I run `python setup.py install` in my virtualenv (output is verbose, though I can provide if requested).

```
$ pip freeze
azure-common==1.0.0
azure-nspkg==1.0.0
azure-storage==0.20.2
azurepoc==0.0.1
futures==3.0.3
python-dateutil==2.4.2
requests==2.8.1
six==1.10.0
wheel==0.24.0
```

At this point, it says that it resolved the dependencies correctly. However, if I try to import the [BlobService module](https://azure.microsoft.com/en-us/documentation/articles/storage-python-how-to-use-blob-storage/) from the command line in my virtualenv:

```
$ python
Python 2.7.10 (default, Oct 12 2015, 16:58:00)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from azure.storage.blob import BlobService
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named storage.blob
```

Here is the directory structure after the setup.py install.

```
$ tree
.
├── azurepoc.egg-info
│   ├── PKG-INFO
│   ├── SOURCES.txt
│   ├── dependency_links.txt
│   ├── requires.txt
│   └── top_level.txt
├── build
│   ├── bdist.macosx-10.11-x86_64
│   └── lib
│       └── poc
│           ├── __init__.py
├── dist
│   └── azurepoc-0.0.1-py2.7.egg
├── poc
│   ├── __init__.py
└── setup.py

7 directories, 11 files
```


As of right now, we've locked ourselves into `azure==0.11.1` because of this issue.

**Comment by zooba** [comment]
@johnpneumann: Any reason you can't use `pip install <path to directory containing your setup.py>` or `pip install -e <path to directory containing your setup.py>`?

Long term, this is the better approach anyway - the Python core teams are trying hard to deprecate direct use of `setup.py`.

**Comment by johnpneumann** [comment]
@zooba - No, there actually isn't a reason that we couldn't use that. I just did a quick test to ensure that the modules imported correctly when I changed to `azure-storage` and tried importing the `BlobService` library and it did (tested on Windows 8, OSX 10.11 and Ubuntu 14.04.3). 

I wasn't aware that there was a push to deprecate the use of `setup.py`. Where's the discussion of this happening so that myself and others can stay aware of this? Is there a pep around it or a mailing list thread that we can follow?

**Comment by zooba** [comment]
[distutils-sig](https://mail.python.org/mailman/listinfo/distutils-sig) is where the discussion happens, though be aware that it's happening at a glacial pace and looks like a lot of side/unrelated issues at times. But the overarching aim is to make as much metadata as possible declarative (e.g. `setup.cfg`) rather than imperative (e.g. `setup.py`).

**Comment by johnpneumann** [comment]
LoL. Rgr. Thanks for the information and helping solve our problem. I hate locking into old versions, so it's much appreciated. Derp on my end with not thinking that through.

**Comment by jehine-MSFT** [comment]
Closing since it looks like you've found a good workaround. Please let us know if you need any more assistance.
Thanks!

**Comment by carlobono** [comment]
this still fails on debian jessie with anaconda python 2.7
described workaround work though.
many thanks!
C
