### ISSUE TITLE
OSError: [Errno 5] Input/output error while downloading large amount of files

### ISSUE THREAD

**Issue by marcelvb** [Azure/azure-storage-python#522]
### Which service(blob, file, queue) does this issue concern?

blob

### Which version of the SDK was used? Please provide the output of `pip freeze`.

I'm using the Azure CLI Version 2.0.47, that according to `az --version` uses version 2.2.2 of the az `storage` module. It comes with it's own version of Python and pip and libs. When I check the directory `/opt/az` I find package `azure-storage-blob` version 1.1.0.

### What problem was encountered?

I'm running the following command to download about 1 TB worth of files from Blob storage to a local disk:
` az storage blob download-batch --max-connections=16 --source my-container --destination /my/local/disk`

After some (long) time and copying half of the files, it crashes:

```
...
Finished[#############################################################]  100.0000%
Finished[#############################################################]  100.0000%
Finished[#############################################################]  100.0000%
Finished[#############################################################]  100.0000%
[Errno 5] Input/output error
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 366, in execute
    cmd.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 234, in new_handler
    handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 177, in handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 151, in storage_blob_download_batch
    for blob_normed in blobs_to_download)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 151, in <genexpr>
    for blob_normed in blobs_to_download)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 124, in _download_blob
    progress_callback=progress_callback)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/blob/baseblobservice.py", line 1872, in get_blob_to_path
    timeout)
OSError: [Errno 5] Input/output error
```

The Azure CLI does not handle the error. While mentioning the issue in the Azure CLI project I was asked to file the issue here (https://github.com/Azure/azure-cli/issues/7346#issuecomment-432975682).

### Have you found a mitigation/solution?

I have used AzCopy instead.

**Comment by zezha-msft** [comment]
Hi @marcelvb, thanks for reaching out!

I see that the exception was thrown from [this line](https://github.com/Azure/azure-multiapi-storage-python/blob/master/azure/multiapi/storage/v2018_03_28/blob/baseblobservice.py#L1872). I'd love to get a bit more information from you so that I can investigate further.

On which platform are you running Azure CLI? And what kind of disk are you downloading data to? Is it possible that the disk filled up? 

Regardless of the reason, I believe Azure CLI can provide a much better experience if they caught the error and skipped the transfer rather than crashing. I've commented on the original thread. Thank you for bringing this issue to our attention.

**Comment by marcelvb** [comment]
It was running on a Ubuntu 16.04.3 LTS machine and writing to a big NAS via a CIFS (Samba) mount. It's very unlikely the disk was full, but there might have been a networking hick-up. My feeling says it was more likely to be a timeout on the source side. It might also have been a very large file (tens of gigabytes) that it was copying. Since the Azure CLI does not print which file it currently copying I have no way to know.

I agree the Azure CLI should catch such errors, continue with the next file and print which files went wrong (see also https://github.com/Azure/azure-cli/issues/6364).

**Comment by zezha-msft** [comment]
Hi @marcelvb, thanks for the information.

Unfortunately, I think the error thrown was not a network error, nor did it come from the Storage Service. I searched for `[Errno 5] Input/output error`, and got the impression that it might be related to writing data to the destination NAS.

Is there a way to verify whether an IO error occurred with your CIFS mount? So that we can narrow down to the source of the problem. Please take a look at [this](https://wiki.samba.org/index.php/LinuxCIFS_troubleshooting). Thanks!

**Comment by zezha-msft** [comment]
@marcelvb any update?
