### ISSUE TITLE
Possible multithread unsafe?

### ISSUE THREAD

**Issue by oak-tree** [Azure/azure-storage-python#559]
### Which service(blob, file, queue) does this issue concern?

`from azure.storage.blob import BlockBlobService

blob_service = BlockBlobService(account_name=conf['name'], account_key=conf['key'])
`

### What problem was encountered?
We are using `threadpool` to do `async` uploading to `storage`. We are creating single `BlockBlobService` and share it across our threads pool. Is it possible that `BlockBlobService` is not a thread safe because it creates `requests.Session()`  at [StorageClient](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-common/azure/storage/common/storageclient.py#L136)

### EDIT
Is it possible that its `threadsafe` because we are working against the same `storage account`?
Thanks!

**Comment by zezha-msft** [comment]
Hi @oak-tree, thanks for reaching out!

To clarify, we make no promise in terms of thread safety, since we could manipulate the session object (like [here](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-common/azure/storage/common/tokencredential.py#L40)). Please consider creating a BlockBlobService for each thread.
