### ISSUE TITLE
INFO messages

### ISSUE THREAD

**Issue by rareal** [Azure/azure-storage-python#619]
### Which service(blob, file, queue) does this issue concern?
file

### Which version of the SDK was used? Please provide the output of `pip freeze`.
Name                    Version                   Build  Channel
azure-common              1.1.23                   pypi_0    pypi
azure-storage-common      2.0.0                    pypi_0    pypi
azure-storage-file        2.0.1                    pypi_0    pypi

### What problem was encountered?
I started receiving a lot of INFO messages after a while in the calls to azure storage, it was working just fine and nothing changed in the environment. I cannot figure out from the documentation what triggered this INFO messages, and as I'm making multiple calls they are filling up my console during debugging. 
Despite the messages the calls work fine, both GET and PUT.
This is the format of the INFO messages I receive, I redacted the ids.

`INFO:azure.storage.common.storageclient:Client-Request-ID=<***> Outgoing request: Method=GET, Path=<***>, Query={'restype': 'directory', 'comp': 'list', 'prefix': None, 'marker': None, 'maxresults': None, 'timeout': None, 'sharesnapshot': None}, Headers={'x-ms-version': '2018-11-09', 'User-Agent': 'Azure-Storage/2.0.0-2.0.1 (Python CPython 3.6.8; Windows 10)', 'x-ms-client-request-id': '<***>', 'x-ms-date': 'Fri, 19 Jul 2019 07:32:30 GMT', 'Authorization': 'REDACTED'}.`

I cannot even find what 'Authorization': 'REDACTED' means.

### Have you found a mitigation/solution?
No

**Comment by xiafu-msft** [comment]
Hi @rareal ,

Thanks so much for reaching out!
This info is logged every time before you send out a request and after you receive a response. 
'Authorization' value is 'REDACTED' because we don't want to log the sensitive credential info.
This INFO is logged by the **_perform_request** method in file **azure/storage/common/storageclient.py**
It doesn't mean something goes wrong, it is just to provide some info. If you want to disable logging, see https://github.com/Azure/azure-storage-python/blob/master/README.rst#logging.
