### ISSUE TITLE
Django FileField/ImageField custom storage for azure blob

### ISSUE THREAD

**Issue by crwilcox** [Azure/azure-storage-python#7]
### Description:
It's possible to customize the loading/saving of files for FileField/ImageField, and it would be nice to have a default implementation which stores it in azure blob storage.

**Comment by jehine-MSFT** [comment]
Thanks for the feature request! We don't plan to work on this scenario at this time, but going forward it's something we may consider once we finish our current work items for the library.

Thanks again!

**Comment by Korijn** [comment]
You can just hook up a custom storage backend in Django that is wired up to Azure, e.g. [django-storages](https://github.com/jschneier/django-storages) and [django-azure-storage](https://github.com/Rediker-Software/django-azure-storage), FileField and ImageField should then "just work".

Unfortunately there's a bug in Django that prevents this, but the fix is included in 1.10 which comes out in a few months, see [here](https://docs.djangoproject.com/en/dev/releases/1.10/#file-storage).

**Comment by jedie** [comment]
> You can just hook up a custom storage backend in Django that is wired up to Azure, e.g. django-storages and django-azure-storage, FileField and ImageField should then "just work".

Both projects are not up-to-date, see:
https://github.com/Rediker-Software/django-azure-storage/issues/8
https://github.com/jschneier/django-storages/issues/476

So there is currently no up-to-date django library for azure storage, isn't it?!?

**Comment by Korijn** [comment]
That is correct.

Also, I recommend against integrating yourself... we went through the exercise and it's been a pain to maintain and keep up to date. There's a lot of Django and azure-storage implementation details that you will need to become aware of as you encounter bugs...

**Comment by jedie** [comment]
> In the end we dropped the integration and just use the azure-storage API directly.

That doesn't sound reasonable to me. Won't you end up implementing your own bridge between azure blob storage and django? Can you elaborate?

**Comment by Korijn** [comment]
We use UUIDs in database to trace back to files in storage. Simple and reliable.

**Comment by jedie** [comment]
Hm. But this is only a very small part of what a azure-storage can actually offer.
