### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by t0yv0** [Azure/azure-storage-python#70]
Is a new release planned that includes a fix for the critical #69 issue? Specifically, when can the fix be expected to appear in PyPI https://pypi.python.org/pypi/azure-storage/0.20.1

**Comment by emgerner-msft** [comment]
We did plan a release but we were hoping to group this with other bugs to avoid an excessive number of tiny releases. Sounds like this is urgent for you though, so would a release by early next week work?

**Comment by t0yv0** [comment]
Sounds good, thank you.

**Comment by t0yv0** [comment]
Any news on this? Thank you.

At this point we've decided to back out of relying on Azure Python SDK entirely at Tachyus, but we would still appreciate a new release from you since this will buy us some time instead of having to deal with this immediately.

Looking back at what went wrong, I realize the mistake I made was assuming that Azure Python SDK is ready for production. More specifically, I depended on Azure Python SDK 2.0 and that introduced azure-storage dependency with 0.20.1 (not 1.x) version. 

You can see how easy it is for people to make this mistake. Azure Python SDK is marked 1.0. I would not do this unless it is stable and production ready, or else not depend on unstable azure-storage from a stable Azure Python SDK... 

CC @ctaggart

**Comment by emgerner-msft** [comment]
Still planning a release today or tomorrow. I'll update when that's out. 

Sorry for any confusion on our side. Just to clarify: If you check the [docs on pip](https://pypi.python.org/pypi/azure/1.0.2) for the Azure package you'll notice none of the packages contained within (storage or otherwise) are at 1.0. The Azure pip package does not contain any code and is simply a wrapper.

We are moving as fast as possible towards a stable 1.0 for storage. Per issue #57 we're working hard on re-vamping the library to all the newest service features after which we'll add some convenience, let things bake, do more testing (etc) and then hopefully call it 1.0. This will take some time though, and it's completely understandable that you need a production library for your service. If there's anything (like this release) we can do to help you stay for now, please do tell! Otherwise, I do hope you'll remain active here and consider moving back again once we get in a more finalized state. If there's any particular features that would make this especially worth if for you please post them in the issue mentioned above or open an issue and we'll do our best!

**Comment by t0yv0** [comment]
Thank you, that totally makes sense. We do have a good option of moving the storage access code to CLR for now, that is, still using Azure Storage but via F#, and then integrating Python-F# separately. Calling AS from Python directly is certainly more convenient, so I will keep an eye out for 1.0.

**Comment by emgerner-msft** [comment]
Release: https://github.com/Azure/azure-storage-python/releases/tag/v0.20.3

**Comment by t0yv0** [comment]
Thank you!
