### ISSUE TITLE
Bug with uploading large files using `put_block_blob_from_path` and specifying content-md5

### ISSUE THREAD

**Issue by gmantri** [Azure/azure-storage-python#99]
I believe there's a bug in uploading large files using `put_block_blob_from_path` and specifying md5 hash of the blob. What I noticed is that when uploading large block blobs, in the code 1st an empty block blob is created (line 1077) which I don't think is needed. Since a user is specifying content-md5 of the file and an empty blob is created by the SDK, their md5 hashes will not match and the user will get an error.

Please see this Stack Overflow thread for more details: http://stackoverflow.com/questions/34914261/python-azure-blob-storage-md5-check-fails-on-blob-upload-using-put-block-blob-fr.

**Comment by emgerner-msft** [comment]
Thanks Gaurav! Will paste my answer from Stack Overflow for reference.

This is sort of an SDK bug in that we should throw a better error message rather than hitting the service, but validating the content of a large upload that has to be chunked simply doesn't work. x_ms_blob_content_md5 will store the md5 but the service will not validate it. That is something you could do on download though. content_md5 is validated by the server for the body of a particular request but since there's more than one with chunked blobs it will never work correctly.

So, if the blob is small enough (below BLOB_MAX_DATA_SIZE) to be put in a single request, content_md5 will work fine. Otherwise I'd simply recommend using HTTPS and storing MD5 in x_ms_blob_content_md5 if you think you might want to download with HTTP and validate it on download. HTTPS already provides validation for things like bit flips on the wire so using it for upload/download will do a lot. If you can't upload/download with HTTPS for one reason or another you can consider chunking the blob yourself using the put block and put block list APIs.

FYI: In future versions we do intend to add automatic MD5 calculation for both single put and chunked operations in the library itself which will fully solve this. For the next version, we will add an improved error message if content_md5 is specified for a chunked download.

**Comment by emgerner-msft** [comment]
As of [0.32.0](https://github.com/Azure/azure-storage-python/releases/tag/v0.32.0) the library supports automatic calculation of transactional MD5s for upload and download. Transactional MD5 is more versatile than stored MD5 as it is computed by the server on the actual stored data. It does not have the issue where the stored content MD5 can get out of date as the blob is updated. Simply use the validate_content MD5 to enable this for the upload of any blob type and blob download. Note that using MD5 validation has a performance penalty and HTTPS already protects against bitflips on the wire so this feature should be used primarily if HTTP is used.

The library does not build in calculation of the total blob MD5 or validate it on download as this historically in other libraries causes issues with the stored MD5 being out of date with the content. However, the user may still set and retrieve this value using the content_settings. Note that by default stored MD5 not returned by the download APIs unless particular provisions are made as described in the get method docs. It can still be retrieved by getting the blob properties.
